Add remaining UML elements
Sage-Bionetworks/challenge-schemas pull request #10
Opened 2020-11-11 03:19 UTC by vpchung

In addition to adding operations for creating and patching a challenge:

- added ROCC logos to docs page
- removed Health endpoints and operations (not needed for ROCC)
- added examples to some of the operations
- make `id` parameters `readOnly` and `password` parameter `writeOnly`

2020-11-11 16:41 UTC, tschaffter requested changes

2020-11-11 16:41 UTC, tschaffter commented on openapi/components/schemas/Challenge.yaml
> +  organizers:
I would rename this property `organizations`

2020-11-11 16:41 UTC, tschaffter commented on openapi/components/schemas/Grant.yaml
> +    type: integer
Change type to string (MongoDB)

2020-11-11 16:41 UTC, tschaffter commented on openapi/components/schemas/Challenge.yaml
> +  organizers: ["Organization1"]
- Rename property `organizations`
- Provide an example of Organization object, not a string (see https://swagger.io/docs/specification/adding-examples/)

2020-11-11 16:41 UTC, tschaffter commented on openapi/components/schemas/Organization.yaml
> +    format: int32
With string type, `uuid` could be an option but it's not an official OpenAPI value. Mongodb ObjectId are also not technically UUID by default (https://en.wikipedia.org/wiki/Universally_unique_identifier). I would just remove `format` for now and add it later if needed.

2020-11-11 16:41 UTC, tschaffter commented on openapi/components/schemas/User.yaml
> +    readOnly: true
This is great! This will solve a problem I was facing in another API.

2020-11-11 16:41 UTC, tschaffter commented on openapi/components/schemas/User.yaml
> +  password:
Add description that says that this field contain the password hash.

2020-11-11 16:41 UTC, tschaffter commented on openapi/components/schemas/User.yaml
> +  password:
Add a string property named `salt` (https://en.wikipedia.org/wiki/Salt_(cryptography))

2020-11-11 16:41 UTC, tschaffter commented on openapi/components/schemas/User.yaml
> +  organizer:
How would this property be used?

2020-11-11 18:31 UTC, vpchung commented on openapi/components/schemas/Challenge.yaml
> +  organizers:
This is actually something I wanted to clarify.

For a challenge, do we want to name the specific people from organizations that are involved in the challenge i.e. what we are currently doing on Synapse? Or should we list the entire organization(s) as our "Partners" (similar to what Kaggle is doing)?

2020-11-11 18:41 UTC, vpchung commented on openapi/components/schemas/Organization.yaml
> +    format: int32
Ah, I played around with `id` a lot; some are `string: uuid`, some are `integer: int32`, and some `string: pattern` :sweat_smile:

I'll stick with a simple `string` for now

2020-11-11 18:55 UTC, vpchung commented on openapi/components/schemas/User.yaml
> +  organizer:
This is a flag I'm using to determine whether an operation is allowed by a user, e.g. only organizers and admins can add/update/remove a challenge.

I don't know if we'll ever need an `admin` user-level, so that property can be removed later.

2020-11-11 19:37 UTC, tschaffter commented on openapi/components/schemas/Challenge.yaml
> +  organizers:
What about:
- Have Challenge.organizers that is a list of Persons
- Have Challenge.organizations that is a list of Organizations. I should keep the name of the property based on the name of the schema used (here Organization).

This comment also suggest to distinguish a Person and User. Depending on the approach we take, Kaggle could be a User.

2020-11-11 19:42 UTC, tschaffter commented on openapi/components/schemas/User.yaml
> +  organizer:
I would add a property `role`, which is an enum that can take the value `admin` and `user` for now.

- `admin`: can do anything
- `user`: can create Challenges, Organizations, etc. and manage the entities they own

2020-11-11 19:55 UTC, vpchung commented on openapi/components/schemas/User.yaml
> +  password:
Adding this to TODO -- add salt hashing for password

2020-11-11 20:34 UTC, vpchung commented on openapi/components/schemas/User.yaml
> +  organizer:
Oh, I like that!

2020-11-12 23:43 UTC, vpchung commented on openapi/components/schemas/Challenge.yaml
> +  organizers:
I decided to do:
- `Challenge.organizers`, where it is a list of Users
- add a relationship between User and Organization by adding `User:organization`

This more closely resembles what the current landscape is providing (and also reflects the UML that I designed). We can definitely restructure/refactor at a later time if needed!

2020-11-13 00:18 UTC, vpchung commented
Since the last review:
- changed all `id` properties to be a simple `string` (for now)
- updated the item-type of `organizers` to be User instead of Organization
- related above, added an `organization` property to the User model

2020-11-13 02:34 UTC, tschaffter commented on openapi/components/schemas/Challenge.yaml
> +  organizers:
> Challenge.organizers, where it is a list of Users

This means that we are enforcing that a person must register as a User of ROCC in order to be able to be listed by someone else as an organizer of a given challenge. This is approach would prevent a platform like Kaggle to automatically register/synchronize challenges on ROCC.

Alternatively, we could have a Person object that has a `name` and `email`. Persons objects can easily be created by a challenge platform. We could use Person objects in the list of challenge organizers.

Imagine the challenge page. We could display the Person information as plain text by default. Now if someone has created a User account on the ROCC portal, we could use the `email` address as an identifier to link the Person and User object. Back the the challenge page, we could then imagine to make the name of challenge organizers who have a ROCC account clickable to go to the profile page of the User selected.

2020-11-13 02:36 UTC, tschaffter commented
> updated the item-type of organizers to be User instead of Organization

See above comment

2020-11-13 02:41 UTC, tschaffter reviewed
See comments added to the discsussion

2020-11-13 04:52 UTC, vpchung commented on openapi/components/schemas/Challenge.yaml
> +  organizers:
That makes sense! So essentially move forward with this design?

<img width="302" alt="Screen Shot 2020-11-12 at 8 51 06 PM" src="https://user-images.githubusercontent.com/9377970/99030001-d22cc100-2528-11eb-93bf-12503daefdb6.png">

I thought from our last discussion, we didn't want to move forward with this idea, but perhaps I misunderstood.

2020-11-13 16:13 UTC, tschaffter commented on openapi/components/schemas/Challenge.yaml
> +  organizers:
Yes, considering the comments below:

- It's a good coding practice to fully spell variable names to improve code readability (`fname` => `firstName`)
- User
  - remove `organizer` and `admin` as discussed previously
  - add `role`
  - add `organization` (the principal org the User belongs to)

2020-11-13 18:31 UTC, vpchung commented on openapi/components/schemas/Challenge.yaml
> +  organizers:
I added a `Person` model, keeping the criteria mentioned above.

2020-11-13 20:55 UTC, tschaffter approved these changes
👍

2020-11-14 09:48 UTC, vpchung commented
Having a hard time signing the previous commits.... so I'm closing this PR and opening another.

2020-11-14 09:48 UTC, closed without merging